### ISSUE TITLE
Initial Login Page

### ISSUE THREAD

**Issue by jessicabojorquez** [cs130-w22/Group-B2#1]
## Epic
This website will have a login page that prompts user to create an account or to login into an existing account. 

## User Stories
- [ ] story #1 Create a front page with webpage logo and 2 options. The first option is create an account for new users or login for returning users.
- [ ] story #2 Create an interface for creating a new profile 
- [ ] story #3 Create an interface for logging into an existing account.
