### ISSUE TITLE
Post Creation Page

### ISSUE THREAD

**Issue by RyanHan0127** [cs130-w22/Group-B2#10]
## User Story
As a user, I want to sell an item, so that other users can see that the item is in the market

## Detailed Description
This page allows user to upload their product post to the database. Thus buyers can search up the item in the catalog page.

## Acceptance Criteria
- [x] Given valid post information, then the user will successfully upload a post
- [x] Given incomplete post information, then the user will be prompted to fix errors

## Tasks
- [x] Create a Post Form in HTML
- [x] Finish Post Form in CSS
- [x] Submitting post form updates database
- [x] Make post viewable in Catalog
