### ISSUE TITLE
Wishlist Page

### ISSUE THREAD

**Issue by RyanHan0127** [cs130-w22/Group-B2#11]
## User Story
As a user, I want to put an item to my wishlist, so that I can look back to it whenever I need to

## Detailed Description
Users will be able to add items to their wishlist, and then accessing this page will allow the user to see the items they saved.

## Acceptance Criteria
- [x] Given a list of products, then I can remove an item if I am not interested.
- [x] Given a post in the wishlist, then I can click on it to either buy it or look at the post description

## Tasks
- [x] Create list of product in a user's wishlist element
- [x] Add website navigation bar on the top (Profile, Map, etc.)
- [x] Design web page using CSS
- [x] Implemenet REST request to either remove the item in wishlist or buy the item
- [x] Implement REST request logic to access post description
- [x] Implement REST response to retrieve wishlist data when user access the page
- [x] Implement web navigation logic
