### ISSUE TITLE
Profile Page

### ISSUE THREAD

**Issue by RyanHan0127** [cs130-w22/Group-B2#12]
## User Story
As a user, I want to access my profile and have other users see who I am. I also want to create a profile if I do not have one yet.

## Detailed Description
Once the user creates their account, then the user will be able to access profile page after verification of a valid UCLA email. Also, users will be able to access seller's profile and see their selling posts.

## Acceptance Criteria
- [x] Given that I logged into my profile, then I can edit and see my information
- [x] Given that I navigates to my profile, then I can click links to navigate to other pages (catalog for example)
- [x] Given that I navigated to a sellers profile, then I can see their profile and posts

## Tasks
- [x] Create profile presentation in columns and rows
- [x] Create section for photo, personal information, links, and posts (include history posts)
- [x] Add link navigation to access other pages of the application
- [x] Design web page using CSS
- [x] Create profile presentation in columns and rows for seller profile
- [x] Create section for photo, (limited) personal information, links, and posts for seller profile
- [x] Add link navigation to access other pages of the application
- [x] Design web page using CSS
