### ISSUE TITLE
Catalog Page

### ISSUE THREAD

**Issue by RyanHan0127** [cs130-w22/Group-B2#13]
## User Story
As a user, I want to search products, so that I can either buy the item or look into the post description.

## Detailed Description
Users will be able to look up products using the filter form and be able to either buy the item if interested already or look into the post description to learn more.

## Acceptance Criteria
- [x] Given filter form, then I will get a list of products that is filterred
- [x] Given a list of products that was filter, then I can scroll and navigate the products of the result
- [x] Given a post in the catalog list, then I can click on it to get more details or buy the item directly

## Tasks
- [x] Create a list of products element
- [x] Create Filter Form
- [x] Add website navigation bar on the top (Profile, Map, etc.)
- [x] Design web page using CSS
- [x] Implement REST request function to retrieve a list of items in DynamoDB
- [x] Implement REST request logic to access post description
- [x] Implement REST response parser to format it correctly to the web page
- [x] Implement web navigation logic
