### ISSUE TITLE
Post Description Page

### ISSUE THREAD

**Issue by RyanHan0127** [cs130-w22/Group-B2#14]
## User Story
As a buyer, I want to see the item description, so that I know more details about that before buying

## Detailed Description
When the user found an item, then the user will be able to see details of the seller's name, location, and pictures.

## Acceptance Criteria
- [x] Given a post, then I will display the description of the product in the post
- [x] Given a list of images, then I will display all images that the user can scroll through
- [x] Given a post, then I will display the seller's information about locations and contact information

##Tasks
- [x] Implement ways to display multiple images that are inputted by the seller
- [x] Implement ways to display description the seller inputs
- [x] Add website navigation bar on the top
- [x] Design web page using CSS
- [x] Implement ways to display seller's information
- [x] Implement ways for user to buy the product
