### ISSUE TITLE
Map Page

### ISSUE THREAD

**Issue by RyanHan0127** [cs130-w22/Group-B2#15]
## User Story
As a buyer, I want to see what items are near me by using the Map feature, so that I know if I can buy the item reasonably

## Detailed Description
Users can use the interactive map to get a better feel on where the product is and can at least let them know if it is feasible to get it.

## Acceptance Criteria
- [x] given item post in catalog, then a marker on the map is created
- [x] given tag on map, then post description page can be accessed
- [x] given all items in catalog, then all items must have a marker on the map
## Tasks
- [x] get a key giving us access to our own instance of a map
- [x] create the HTML and CSS page to put the map on
- [x] retrieve the data representing an item post in json
- [x] convert the data into a REST call for all data that needs a place on the map
- [x] verify that the data from the items are placed on the map after a REST call
- [x] be able to access the item description from the marker on the map
