### ISSUE TITLE
Messaging Page

### ISSUE THREAD

**Issue by RyanHan0127** [cs130-w22/Group-B2#16]
## User Story
As a buyer, I want to message the seller, so that I can ask for negotiations, last minute questions, and ask how the buyer wants to pickup the item.

## Detailed Description
Users will be able to use the messaging service to contact the seller. There, buyers can negotiate price if needed and ask what's the best way to get the item.

## Acceptance Criteria
- [ ] Given a chat selection, then the user will correctly see the chat history with the recipient 
- [ ] Given a sent message, then the user will correctly see the updated chat history 
- [ ] Given a new contact, then the user will be able to initiate a new chat history

## Tasks 
- [ ] implement firebase messaging to successfully store message history 
- [ ] correctly parse firebase message data for relevant information 
- [ ] acquire message history upon selecting a contact 
- [ ] correctly update firebase with new messages 
- [ ] format the messages nicely 
- [ ] make the webpage display formatted chat history 
- [ ] allow selection between multiple contacts on the webpage
- [ ] implement initiation of new messages
