### ISSUE TITLE
Implement secure logging in 

### ISSUE THREAD

**Issue by jessicabojorquez** [cs130-w22/Group-B2#2]
## Epic
Ensure that only students can create accounts in this website

## User Stories
- [ ] story #4 Implement: Verification of email that ends with .edu
- [ ] story #5 Implement: Send verification email 6 digit code to user email and create account only when verified 
- [ ] story #6 Implement: Ask user to input the 6 digit code
- [ ]  story #7 Implement: If 6 digit code is correct then create account
