### ISSUE TITLE
Main page

### ISSUE THREAD

**Issue by jessicabojorquez** [cs130-w22/Group-B2#3]
## Epic
Front page after logging in with tabs for news, profile, messages, map display, interested-marked items

## User Stories
- [ ] story #8 Create initial front page after logging in. This page should contain 5 tabs at the top. 
- [ ] story #9 Implement news message that displays posts made by other users or the logged in user.
- [ ] story #10 Add sections to profile tab for entering personal information with Edit and Save options. This tab will have "editing" mode and "saved" mode. Editing mode will have entries with cursor to enter information and Saved mode will simply display without having option to edit information. 
- [ ] story #11 Implement Message chat interface with list of "active" chats. Active chats are any chats that have been created and not delted. 
- [ ] story #12 Implement map display
- [ ] story #13 Implement a tab that behaves the same as the "news" tab but only displays posts that have been previously liked, or added to bucket list.
