### ISSUE TITLE
Profile Features

### ISSUE THREAD

**Issue by jessicabojorquez** [cs130-w22/Group-B2#4]
## Epic
Each profile should have a section for personal information, a shopping cart, a "shop", an interest bucket, and a wish list. The shopping cart will list all items that user has picked to buy or pick up with a computation of total payment with tax (if there is one). The "shop" will contain any post made by the user for items they have available for pick up or sale. The interest bucket will have any posts made by other sellers that I have saved to potentially buy later without having to search again. The wish list can have a list of keywords that represent items the user is interested in buying, this can be used to implement a recommendation system, it is also optional and if there are no keywords entered, the user gets random posts in the "news" tab. This last section can also have 2 options for large items (such as furniture) or small items (such as books or clothes or lamps that can be carried), and it can be checkmarks. The user will also have a karma score as a seller and a buyer.

## User Stories
- [ ] story #14 Implement personal information tab that has name, email (optional to display), phone number (optional), university.
- [ ] story #15 Implement shopping cart. This will contain list of items you are buying, the total before tax, tax, and total after tax.
- [ ] story #16 Implement shop. This will list posts of items available to sell. They will be visible for the owner of the profile and for visitors of profile. Each post will require to enter a deadline for pick u, or a non-deadline option in case there is no rush to sell an item. Lastly this item will have a method of payment. 
- [ ] story # 17 Implement Interest bucket. This will have all post that user has intentionally added to this bucket to look at later without having to search for them.
- [ ] story #18 Implement Wishlist. This will only be visible for owner of profile and it can consist of just a list of items that user will potentially be interested in. 
- [ ] story #19 Implement Karma score. This will appear next to user name. It will consist of 2 scores: 1 score as a seller and 1 score as a buyer.
