### ISSUE TITLE
Free And For Sale

### ISSUE THREAD

**Issue by RyanHan0127** [cs130-w22/Group-B2#8]
## Epic
There are many shopping sites that serves its purposes. This "Free And For Sale" web application is more focused towards UCLA students, who wants to look for used items or find something cheap from other UCLA students. The students will be able to make an account to search for items near UCLA, buy the item, store that item to their wishlist, and be able to chat with the seller to negotiate any last details.

## User Stories
- [x] story #9 As a user, I want to create an account, so that I can be able to access the catalog page and start buying
- [x] story #10 As a user, I want to sell an item, so that other users can see that the item is in the market
- [x] story #11 As a user, I want to put an item to my wishlist, so that I can look back to it whenever I need to
- [x] story #12 As a user, I want to access my profile information, so that in case I can verify it correctly and other users can see who I am.
- [x] story #13 As a user, I want to search products, so that I can either buy the item or look into the post description.
- [x] story #14 As a buyer, I want to see the item description, so that I know more details about that before buying
- [x] story #15 As a buyer, I want to see what items are near me by using the Map feature, so that I know if I can buy the item reasonably
- [ ] story #16 As a buyer, I want to message the seller, so that I can ask for negotiations, last minute questions, and ask how the buyer wants to pickup the item.
