### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by RyanHan0127** [cs130-w22/Group-B2#9]
## User Story
As a user, I want to log in or create an account, so that I can be able to access the catalog page and start buying.

## Detailed Description
This tab will allow users to log in or create an account with email verification.

## Acceptance Criteria
- [x] Given the login page, then I can put my username and password in the login page
- [x] Given the username and password, then I can be redirected to the product catalog page
- [x] Given a new user, then I can create an account and redirect me to email verification

## Tasks
- [x] Develop system to check for g.ucla.edu domain
- [x] Implement system to check that password matches username
- [x] Link user name, email, phone number, and address under one profile
- [ ] Send, receive, and verify email verification passcode
- [x] Design web page using CSS
- [x] Check for formatting for user inputs when creating account
